// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: processing.sql

package dbsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkProcessingLease = `-- name: CheckProcessingLease :one
SELECT EXISTS(SELECT 1 FROM workflow.processing_runs
 WHERE id=$1 AND lease_owner=$2 AND fence=$3 AND lease_until>now())
`

type CheckProcessingLeaseParams struct {
	ID         pgtype.UUID
	LeaseOwner pgtype.UUID
	Fence      int64
}

func (q *Queries) CheckProcessingLease(ctx context.Context, arg CheckProcessingLeaseParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkProcessingLease, arg.ID, arg.LeaseOwner, arg.Fence)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkProcessingSchema = `-- name: CheckProcessingSchema :exec
SELECT r.id,r.project_id,r.revision,r.state,r.owner_issuer,r.owner_subject,r.snapshot,r.lease_owner,r.lease_until,r.fence,
 c.command_id,c.request_digest,c.response,e.sequence,e.event,a.intent,s.result,v.review,p.approval
FROM workflow.processing_runs r,workflow.processing_commands c,workflow.processing_events e,
workflow.processing_attempts a,workflow.processing_results s,workflow.processing_reviews v,workflow.processing_approvals p LIMIT 0
`

func (q *Queries) CheckProcessingSchema(ctx context.Context) error {
	_, err := q.db.Exec(ctx, checkProcessingSchema)
	return err
}

const claimProcessingRun = `-- name: ClaimProcessingRun :one
UPDATE workflow.processing_runs SET lease_owner=$1,lease_until=now()+interval '60 seconds',fence=fence+1
WHERE id=(SELECT id FROM workflow.processing_runs
 WHERE state IN ('verifying','queued','running','validating','cancelling','uncertain')
 AND (lease_until IS NULL OR lease_until<now())
 ORDER BY updated_at FOR UPDATE SKIP LOCKED LIMIT 1)
RETURNING snapshot,fence
`

type ClaimProcessingRunRow struct {
	Snapshot []byte
	Fence    int64
}

func (q *Queries) ClaimProcessingRun(ctx context.Context, leaseOwner pgtype.UUID) (ClaimProcessingRunRow, error) {
	row := q.db.QueryRow(ctx, claimProcessingRun, leaseOwner)
	var i ClaimProcessingRunRow
	err := row.Scan(&i.Snapshot, &i.Fence)
	return i, err
}

const createProcessingRun = `-- name: CreateProcessingRun :exec
INSERT INTO workflow.processing_runs(id,project_id,revision,state,owner_issuer,owner_subject,snapshot)
VALUES($1,$2,$3,$4,$5,$6,$7)
`

type CreateProcessingRunParams struct {
	ID           pgtype.UUID
	ProjectID    pgtype.UUID
	Revision     int64
	State        string
	OwnerIssuer  string
	OwnerSubject string
	Snapshot     []byte
}

func (q *Queries) CreateProcessingRun(ctx context.Context, arg CreateProcessingRunParams) error {
	_, err := q.db.Exec(ctx, createProcessingRun,
		arg.ID,
		arg.ProjectID,
		arg.Revision,
		arg.State,
		arg.OwnerIssuer,
		arg.OwnerSubject,
		arg.Snapshot,
	)
	return err
}

const findProcessingCommand = `-- name: FindProcessingCommand :one
SELECT request_digest, response FROM workflow.processing_commands
WHERE project_id = $1 AND issuer = $2 AND subject = $3 AND command_id = $4
`

type FindProcessingCommandParams struct {
	ProjectID pgtype.UUID
	Issuer    string
	Subject   string
	CommandID pgtype.UUID
}

type FindProcessingCommandRow struct {
	RequestDigest string
	Response      []byte
}

func (q *Queries) FindProcessingCommand(ctx context.Context, arg FindProcessingCommandParams) (FindProcessingCommandRow, error) {
	row := q.db.QueryRow(ctx, findProcessingCommand,
		arg.ProjectID,
		arg.Issuer,
		arg.Subject,
		arg.CommandID,
	)
	var i FindProcessingCommandRow
	err := row.Scan(&i.RequestDigest, &i.Response)
	return i, err
}

const listProcessingEvents = `-- name: ListProcessingEvents :many
SELECT sequence,event FROM workflow.processing_events WHERE run_id=$1 AND sequence>$2 ORDER BY sequence LIMIT 101
`

type ListProcessingEventsParams struct {
	RunID    pgtype.UUID
	Sequence int64
}

type ListProcessingEventsRow struct {
	Sequence int64
	Event    []byte
}

func (q *Queries) ListProcessingEvents(ctx context.Context, arg ListProcessingEventsParams) ([]ListProcessingEventsRow, error) {
	rows, err := q.db.Query(ctx, listProcessingEvents, arg.RunID, arg.Sequence)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProcessingEventsRow
	for rows.Next() {
		var i ListProcessingEventsRow
		if err := rows.Scan(&i.Sequence, &i.Event); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProcessingRuns = `-- name: ListProcessingRuns :many
SELECT snapshot FROM workflow.processing_runs
WHERE project_id=$1 AND ($2::uuid IS NULL OR id > $2::uuid)
ORDER BY id LIMIT 11
`

type ListProcessingRunsParams struct {
	ProjectID pgtype.UUID
	Cursor    pgtype.UUID
}

func (q *Queries) ListProcessingRuns(ctx context.Context, arg ListProcessingRunsParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listProcessingRuns, arg.ProjectID, arg.Cursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var snapshot []byte
		if err := rows.Scan(&snapshot); err != nil {
			return nil, err
		}
		items = append(items, snapshot)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProcessingProject = `-- name: LockProcessingProject :one
SELECT id FROM workflow.projects WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockProcessingProject(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockProcessingProject, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const lockProcessingRun = `-- name: LockProcessingRun :one
SELECT snapshot FROM workflow.processing_runs WHERE project_id=$1 AND id=$2 FOR UPDATE
`

type LockProcessingRunParams struct {
	ProjectID pgtype.UUID
	ID        pgtype.UUID
}

func (q *Queries) LockProcessingRun(ctx context.Context, arg LockProcessingRunParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, lockProcessingRun, arg.ProjectID, arg.ID)
	var snapshot []byte
	err := row.Scan(&snapshot)
	return snapshot, err
}

const processingRoles = `-- name: ProcessingRoles :many
SELECT role FROM workflow.project_memberships
WHERE project_id = $1 AND issuer = $2 AND subject = $3 FOR SHARE
`

type ProcessingRolesParams struct {
	ProjectID pgtype.UUID
	Issuer    string
	Subject   string
}

func (q *Queries) ProcessingRoles(ctx context.Context, arg ProcessingRolesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, processingRoles, arg.ProjectID, arg.Issuer, arg.Subject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readProcessingApproval = `-- name: ReadProcessingApproval :one
SELECT approval FROM workflow.processing_approvals WHERE run_id=$1 AND id=$2
`

type ReadProcessingApprovalParams struct {
	RunID pgtype.UUID
	ID    pgtype.UUID
}

func (q *Queries) ReadProcessingApproval(ctx context.Context, arg ReadProcessingApprovalParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, readProcessingApproval, arg.RunID, arg.ID)
	var approval []byte
	err := row.Scan(&approval)
	return approval, err
}

const readProcessingResult = `-- name: ReadProcessingResult :one
SELECT r.result FROM workflow.processing_results r
JOIN workflow.processing_attempts a ON a.id=r.attempt_id
WHERE a.run_id=$1 AND a.id=$2
`

type ReadProcessingResultParams struct {
	RunID pgtype.UUID
	ID    pgtype.UUID
}

func (q *Queries) ReadProcessingResult(ctx context.Context, arg ReadProcessingResultParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, readProcessingResult, arg.RunID, arg.ID)
	var result []byte
	err := row.Scan(&result)
	return result, err
}

const readProcessingRun = `-- name: ReadProcessingRun :one
SELECT snapshot FROM workflow.processing_runs WHERE project_id=$1 AND id=$2
`

type ReadProcessingRunParams struct {
	ProjectID pgtype.UUID
	ID        pgtype.UUID
}

func (q *Queries) ReadProcessingRun(ctx context.Context, arg ReadProcessingRunParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, readProcessingRun, arg.ProjectID, arg.ID)
	var snapshot []byte
	err := row.Scan(&snapshot)
	return snapshot, err
}

const releaseProcessingLease = `-- name: ReleaseProcessingLease :exec
UPDATE workflow.processing_runs SET lease_owner=NULL,lease_until=NULL,updated_at=now()
WHERE id=$1 AND lease_owner=$2 AND fence=$3
`

type ReleaseProcessingLeaseParams struct {
	ID         pgtype.UUID
	LeaseOwner pgtype.UUID
	Fence      int64
}

func (q *Queries) ReleaseProcessingLease(ctx context.Context, arg ReleaseProcessingLeaseParams) error {
	_, err := q.db.Exec(ctx, releaseProcessingLease, arg.ID, arg.LeaseOwner, arg.Fence)
	return err
}

const renewProcessingLease = `-- name: RenewProcessingLease :execrows
UPDATE workflow.processing_runs SET lease_until=now()+interval '60 seconds'
WHERE id=$1 AND lease_owner=$2 AND fence=$3 AND lease_until>now() AND revision=$4
`

type RenewProcessingLeaseParams struct {
	ID         pgtype.UUID
	LeaseOwner pgtype.UUID
	Fence      int64
	Revision   int64
}

func (q *Queries) RenewProcessingLease(ctx context.Context, arg RenewProcessingLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewProcessingLease,
		arg.ID,
		arg.LeaseOwner,
		arg.Fence,
		arg.Revision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveProcessingApproval = `-- name: SaveProcessingApproval :exec
INSERT INTO workflow.processing_approvals(id,run_id,approval) VALUES($1,$2,$3)
`

type SaveProcessingApprovalParams struct {
	ID       pgtype.UUID
	RunID    pgtype.UUID
	Approval []byte
}

func (q *Queries) SaveProcessingApproval(ctx context.Context, arg SaveProcessingApprovalParams) error {
	_, err := q.db.Exec(ctx, saveProcessingApproval, arg.ID, arg.RunID, arg.Approval)
	return err
}

const saveProcessingAttempt = `-- name: SaveProcessingAttempt :exec
INSERT INTO workflow.processing_attempts(id,run_id,number,intent) VALUES($1,$2,$3,$4)
`

type SaveProcessingAttemptParams struct {
	ID     pgtype.UUID
	RunID  pgtype.UUID
	Number int32
	Intent []byte
}

func (q *Queries) SaveProcessingAttempt(ctx context.Context, arg SaveProcessingAttemptParams) error {
	_, err := q.db.Exec(ctx, saveProcessingAttempt,
		arg.ID,
		arg.RunID,
		arg.Number,
		arg.Intent,
	)
	return err
}

const saveProcessingCommand = `-- name: SaveProcessingCommand :exec
INSERT INTO workflow.processing_commands(project_id,issuer,subject,command_id,request_digest,response)
VALUES ($1,$2,$3,$4,$5,$6)
`

type SaveProcessingCommandParams struct {
	ProjectID     pgtype.UUID
	Issuer        string
	Subject       string
	CommandID     pgtype.UUID
	RequestDigest string
	Response      []byte
}

func (q *Queries) SaveProcessingCommand(ctx context.Context, arg SaveProcessingCommandParams) error {
	_, err := q.db.Exec(ctx, saveProcessingCommand,
		arg.ProjectID,
		arg.Issuer,
		arg.Subject,
		arg.CommandID,
		arg.RequestDigest,
		arg.Response,
	)
	return err
}

const saveProcessingEvent = `-- name: SaveProcessingEvent :exec
INSERT INTO workflow.processing_events(run_id,revision,event) VALUES($1,$2,$3)
`

type SaveProcessingEventParams struct {
	RunID    pgtype.UUID
	Revision int64
	Event    []byte
}

func (q *Queries) SaveProcessingEvent(ctx context.Context, arg SaveProcessingEventParams) error {
	_, err := q.db.Exec(ctx, saveProcessingEvent, arg.RunID, arg.Revision, arg.Event)
	return err
}

const saveProcessingResult = `-- name: SaveProcessingResult :exec
INSERT INTO workflow.processing_results(attempt_id,result) VALUES($1,$2)
`

type SaveProcessingResultParams struct {
	AttemptID pgtype.UUID
	Result    []byte
}

func (q *Queries) SaveProcessingResult(ctx context.Context, arg SaveProcessingResultParams) error {
	_, err := q.db.Exec(ctx, saveProcessingResult, arg.AttemptID, arg.Result)
	return err
}

const saveProcessingReview = `-- name: SaveProcessingReview :exec
INSERT INTO workflow.processing_reviews(id,run_id,review) VALUES($1,$2,$3)
`

type SaveProcessingReviewParams struct {
	ID     pgtype.UUID
	RunID  pgtype.UUID
	Review []byte
}

func (q *Queries) SaveProcessingReview(ctx context.Context, arg SaveProcessingReviewParams) error {
	_, err := q.db.Exec(ctx, saveProcessingReview, arg.ID, arg.RunID, arg.Review)
	return err
}

const updateProcessingRun = `-- name: UpdateProcessingRun :execrows
UPDATE workflow.processing_runs SET revision=revision+1,state=$3,snapshot=$4,updated_at=now()
WHERE id=$1 AND revision=$2
`

type UpdateProcessingRunParams struct {
	ID       pgtype.UUID
	Revision int64
	State    string
	Snapshot []byte
}

func (q *Queries) UpdateProcessingRun(ctx context.Context, arg UpdateProcessingRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProcessingRun,
		arg.ID,
		arg.Revision,
		arg.State,
		arg.Snapshot,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
