// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package dbsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAuthorizedProjects = `-- name: ListAuthorizedProjects :many
SELECT p.id, p.name,
    array_agg(m.role ORDER BY CASE m.role
        WHEN 'capture' THEN 0 WHEN 'process' THEN 1
        WHEN 'review' THEN 2 WHEN 'enroll' THEN 3 END)::text[] AS roles
FROM workflow.projects AS p
JOIN workflow.project_memberships AS m ON m.project_id = p.id
WHERE m.issuer = $1
    AND m.subject = $2
    AND ($3::uuid IS NULL OR p.id > $3::uuid)
GROUP BY p.id, p.name
ORDER BY p.id
LIMIT $4
`

type ListAuthorizedProjectsParams struct {
	Issuer   string
	Subject  string
	Cursor   pgtype.UUID
	PageSize int32
}

type ListAuthorizedProjectsRow struct {
	ID    pgtype.UUID
	Name  string
	Roles []string
}

func (q *Queries) ListAuthorizedProjects(ctx context.Context, arg ListAuthorizedProjectsParams) ([]ListAuthorizedProjectsRow, error) {
	rows, err := q.db.Query(ctx, listAuthorizedProjects,
		arg.Issuer,
		arg.Subject,
		arg.Cursor,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuthorizedProjectsRow
	for rows.Next() {
		var i ListAuthorizedProjectsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Roles); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
