// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: readiness.sql

package dbsql

import (
	"context"
)

const checkProjectSchema = `-- name: CheckProjectSchema :exec
SELECT p.id, p.name, p.created_at,
       m.project_id, m.issuer, m.subject, m.role
FROM workflow.projects AS p
LEFT JOIN workflow.project_memberships AS m ON m.project_id = p.id
LIMIT 0
`

func (q *Queries) CheckProjectSchema(ctx context.Context) error {
	_, err := q.db.Exec(ctx, checkProjectSchema)
	return err
}

const hasLegacyMigrationLedger = `-- name: HasLegacyMigrationLedger :one

SELECT (to_regclass('workflow.schema_migrations') IS NOT NULL)::boolean AS present
`

// Readiness must never call Goose's Status/GetDBVersion: those can initialize
// its version table. These queries are strictly read-only and bounded.
func (q *Queries) HasLegacyMigrationLedger(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, hasLegacyMigrationLedger)
	var present bool
	err := row.Scan(&present)
	return present, err
}

const listMigrationVersions = `-- name: ListMigrationVersions :many
SELECT version_id, is_applied
FROM public.workflow_goose_db_version
ORDER BY version_id
LIMIT $1::integer
`

type ListMigrationVersionsRow struct {
	VersionID int64
	IsApplied bool
}

func (q *Queries) ListMigrationVersions(ctx context.Context, maxVersions int32) ([]ListMigrationVersionsRow, error) {
	rows, err := q.db.Query(ctx, listMigrationVersions, maxVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMigrationVersionsRow
	for rows.Next() {
		var i ListMigrationVersionsRow
		if err := rows.Scan(&i.VersionID, &i.IsApplied); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
