-- sqlc-only description of Goose v3's PostgreSQL version table.
-- Goose creates/owns this table. This file is NOT an application migration and
-- is never executed by Workflow. Keep it aligned when upgrading Goose.
CREATE TABLE public.workflow_goose_db_version (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp NOT NULL DEFAULT now()
);
